INSERT INTO recruiting_data.category (name, description) VALUES
                                             ('Backend Development', 'Development of server-side applications, APIs, and databases'),
                                             ('Frontend Development', 'Development of client-side applications, web interfaces, and user experience'),
                                             ('Full Stack Development', 'Development covering both backend and frontend components'),
                                             ('DevOps Engineering', 'Automation, deployment, and infrastructure management for software projects'),
                                             ('Mobile Development', 'Development of mobile applications for iOS and Android'),
                                             ('Game Development', 'Design and development of video games and interactive media'),
                                             ('AI Engineering', 'Engineering and deployment of artificial intelligence systems'),
                                             ('Machine Learning', 'Creating models that learn from data to make predictions or decisions'),
                                             ('Data Analytics', 'Analyzing datasets to uncover insights and trends'),
                                             ('Data Science', 'Interpreting complex data to guide business decisions'),
                                             ('Cybersecurity', 'Protecting systems and data from cyber threats'),
                                             ('QA & Testing', 'Testing software to ensure quality and reliability'),
                                             ('UI Design', 'Designing user interfaces for digital products'),
                                             ('UX Design', 'Enhancing user experience and usability of products'),
                                             ('Database Administration', 'Managing and maintaining database systems'),
                                             ('System Administration', 'Maintaining IT infrastructure and servers'),
                                             ('Network Administration', 'Managing and configuring computer networks'),
                                             ('Cloud Computing', 'Deploying and managing services on cloud platforms'),
                                             ('IoT', 'Developing Internet of Things applications and devices'),
                                             ('Blockchain Development', 'Creating blockchain-based applications and smart contracts'),
                                             ('Data Engineering', 'Building pipelines and infrastructure for data processing'),
                                             ('Server Administration', 'Managing servers and back-end systems'),
                                             ('Networking', 'Designing and managing network architectures'),
                                             ('NoSQL Databases', 'Working with non-relational database systems'),
                                             ('SQL Databases', 'Managing relational database systems'),
                                             ('API Development', 'Designing and developing application programming interfaces'),
                                             ('Test Engineering', 'Engineering processes for automated and manual testing'),
                                             ('Microservices Development', 'Creating distributed, modular software systems'),
                                             ('Financial Analysis', 'Analyzing financial data to guide decision-making'),
                                             ('Accounting', 'Managing financial records and bookkeeping'),
                                             ('Auditing', 'Examining financial records for compliance and accuracy'),
                                             ('Taxation', 'Managing taxes and ensuring regulatory compliance'),
                                             ('Investment Banking', 'Providing financial advisory and capital services'),
                                             ('Corporate Finance', 'Managing company finances and capital structures'),
                                             ('Financial Planning', 'Planning and forecasting financial goals'),
                                             ('Insurance', 'Managing risk coverage and insurance policies'),
                                             ('Asset Management', 'Managing investment portfolios and assets'),
                                             ('Risk Management', 'Identifying and mitigating financial and operational risks'),
                                             ('Credit Analysis', 'Assessing creditworthiness and loan risks'),
                                             ('FinTech', 'Technology solutions for financial services'),
                                             ('Financial Consulting', 'Providing expert financial advice'),
                                             ('Banking Operations', 'Managing daily banking activities'),
                                             ('Retirement Planning', 'Planning for future retirement needs'),
                                             ('Valuation', 'Evaluating the worth of assets or companies'),
                                             ('Treasury', 'Managing company cash flow and liquidity'),
                                             ('Capital Management', 'Optimizing capital allocation'),
                                             ('Financial Reporting', 'Preparing and presenting financial statements'),
                                             ('Financial Control', 'Ensuring compliance and controlling financial processes'),
                                             ('Physicians', 'Medical doctors providing healthcare services'),
                                             ('Nurses', 'Providing patient care and support'),
                                             ('Pharmacists', 'Dispensing medications and advising patients'),
                                             ('Physical Therapists', 'Helping patients improve mobility and manage pain'),
                                             ('Dental Specialists', 'Providing oral health care and treatments'),
                                             ('Psychologists', 'Providing mental health support and counseling'),
                                             ('Psychiatrists', 'Diagnosing and treating mental health disorders'),
                                             ('Laboratory Technicians', 'Performing lab tests and experiments'),
                                             ('Medical Researchers', 'Conducting research to advance medical knowledge'),
                                             ('Medical Administrators', 'Managing healthcare facilities and operations'),
                                             ('Emergency Medical Services', 'Providing urgent medical care'),
                                             ('Rehabilitation Specialists', 'Assisting patients with recovery and therapy'),
                                             ('Medical Assistants', 'Supporting healthcare professionals with patient care'),
                                             ('Medical Technologists', 'Operating medical equipment and diagnostics'),
                                             ('Medical Consultants', 'Providing medical advice and expertise'),
                                             ('Medical Writers', 'Writing medical content and documentation'),
                                             ('Pharmaceutical Representatives', 'Promoting and selling medications'),
                                             ('Pharmaceutical Researchers', 'Researching new drugs and therapies'),
                                             ('Medical Translators', 'Translating medical documents and communication'),
                                             ('Medical Lawyers', 'Legal experts in healthcare law'),
                                             ('Teachers', 'Educating students across various subjects'),
                                             ('Professors', 'Teaching and conducting research at universities'),
                                             ('Researchers', 'Conducting scientific and academic research'),
                                             ('Educational Consultants', 'Providing guidance on educational strategies'),
                                             ('Educational Psychologists', 'Supporting student learning and development'),
                                             ('Training Specialists', 'Designing and delivering professional training'),
                                             ('School Administrators', 'Managing schools and educational institutions'),
                                             ('Librarians', 'Organizing and managing information resources'),
                                             ('Technical Writers', 'Creating documentation and manuals for technology'),
                                             ('Courses & Training', 'Providing structured learning opportunities'),
                                             ('EdTech', 'Technology solutions for education'),
                                             ('Scientific Editors', 'Editing academic and scientific content'),
                                             ('Mathematicians', 'Solving problems using mathematics'),
                                             ('Physicists', 'Studying the principles of physics and matter'),
                                             ('Chemists', 'Analyzing chemical compounds and reactions'),
                                             ('Biologists', 'Studying living organisms and ecosystems'),
                                             ('Ecologists', 'Researching environmental systems and sustainability'),
                                             ('Geographers', 'Studying earth systems and spatial relationships'),
                                             ('Archaeologists', 'Studying past human cultures and artifacts'),
                                             ('Historians', 'Researching and analyzing historical events'),
                                             ('Linguists', 'Studying language structure and development'),
                                             ('Sociologists', 'Analyzing human society and social behavior'),
                                             ('Economists', 'Studying economic systems and markets'),
                                             ('Lawyers', 'Providing legal counsel and representation'),
                                             ('Journalists', 'Reporting and investigating news'),
                                             ('Editors', 'Reviewing and refining written content'),
                                             ('Translators', 'Converting text between languages'),
                                             ('Publicists', 'Managing public image and communications'),
                                             ('Copywriters', 'Writing marketing and promotional content'),
                                             ('Marketing Specialists', 'Planning and executing marketing campaigns'),
                                             ('Sales Representatives', 'Selling products and services to customers'),
                                             ('Customer Support', 'Providing assistance and resolving customer issues'),
                                             ('Project Management', 'Planning and managing projects to completion'),
                                             ('Human Resources', 'Managing employee relations and HR processes'),
                                             ('Recruitment', 'Hiring and onboarding new employees'),
                                             ('Legal Compliance', 'Ensuring adherence to laws and regulations'),
                                             ('Operations Management', 'Overseeing day-to-day business operations'),
                                             ('Supply Chain Management', 'Managing logistics and supply networks'),
                                             ('Manufacturing', 'Producing goods and managing production processes'),
                                             ('Construction', 'Planning and executing building projects'),
                                             ('Engineering', 'Designing and developing technical solutions'),
                                             ('Architecture', 'Designing buildings and urban spaces'),
                                             ('Creative Arts', 'Producing visual, performance, or literary arts'),
                                             ('Design', 'Creating visual, industrial, or graphic designs'),
                                             ('Photography', 'Capturing images for artistic or commercial use'),
                                             ('Videography', 'Creating video content for media or marketing'),
                                             ('Music & Audio', 'Producing and performing music and audio content'),
                                             ('Hospitality', 'Managing hotels, restaurants, and tourism services'),
                                             ('Food & Beverage', 'Preparing and serving food and drinks'),
                                             ('Retail', 'Selling goods directly to consumers'),
                                             ('Logistics', 'Coordinating transportation and delivery of goods'),
                                             ('Transportation', 'Operating vehicles and transportation systems'),
                                             ('Real Estate', 'Managing property sales, leasing, and development'),
                                             ('Consulting', 'Providing expert advice in various fields'),
                                             ('Entrepreneurship', 'Starting and managing new businesses'),
                                             ('Customer Experience', 'Improving customer satisfaction and loyalty');
